# Generated by Django 5.0.4 on 2024-05-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(max_length=200)),
                ('html_url', models.URLField()),
                ('stargazers_count', models.IntegerField(default=0)),
                ('watchers_count', models.IntegerField(default=0)),
                ('forks_count', models.IntegerField(default=0)),
            ],
        ),
    ]
